name: Scribe SLSA Provanence evidence generator
description: Collect, Create and Store SLSA provenance evidence
author: Mikey Strauss
outputs:
  OUTPUT_PATH:
    description: evidence output file path
    value: ""
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>]
    required: true
  all-env:
    description: Attach all environment variables
  attest-config:
    description: Attestation config path
  attest-default:
    description: Attestation default config, options=[sigstore sigstore-github x509 x509-env kms pubkey]
  build-type:
    description: Set build type
  builder-id:
    description: Set builder id
  by-product:
    description: Attach by product path
  ca:
    description: x509 CA Chain path
  cert:
    description: x509 Cert path
  components:
    description: Select by products components groups, options=[metadata layers packages syft files dep commits]
  crl:
    description: x509 CRL path
  crl-full-chain:
    description: Enable Full chain CRL verfication
  depth:
    description: Git clone depth
  disable-crl:
    description: Disable certificate revocation verificatoin
  external:
    description: Add build external parameters
  finished-on:
    description: Set metadata finished time (YYYY-MM-DDThh:mm:ssZ)
  force:
    description: Force overwrite cache
  format:
    description: Evidence format, options=[statement attest]
  git-auth:
    description: 'Git repository authentication info, [format: ''username:password'']'
  git-branch:
    description: Git branch in the repository
  git-commit:
    description: Git commit hash in the repository
  git-tag:
    description: Git tag in the repository
  invocation:
    description: Set metadata invocation ID
  key:
    description: x509 Private key path
  kms:
    description: Provide KMS key reference
  oci:
    description: Enable OCI store
  oci-repo:
    description: Select OCI custom attestation repo
  pass:
    description: Private key password
  payload:
    description: path of the decoded payload
  platform:
    description: Select target platform, examples=windows/armv6, arm64 ..)
  predicate:
    description: Import predicate path
  pubkey:
    description: Public key path
  started-on:
    description: Set metadata started time (YYYY-MM-DDThh:mm:ssZ)
  statement:
    description: Import statement path
  cache-enable:
    description: Enable local cache
  config:
    description: Configuration file path
  deliverable:
    description: Mark as deliverable, options=[true, false]
  env:
    description: Environment keys to include in evidence
  gate:
    description: Policy Gate name
  label:
    description: Add Custom labels
  level:
    description: Log depth level, options=[panic fatal error warning info debug trace]
  log-context:
    description: Attach context to all logs
  log-file:
    description: Output log to file
  output-directory:
    description: Output directory path
    default: ./scribe/valint
  output-file:
    description: Output file name
  pipeline-name:
    description: Pipeline name
  predicate-type:
    description: Custom Predicate type (generic evidence format)
  product-key:
    description: Product Key
  product-version:
    description: Product Version
  scribe-client-id:
    description: Scribe Client ID (deprecated)
  scribe-client-secret:
    description: Scribe Client Token
  scribe-disable:
    description: Disable scribe client
  scribe-enable:
    description: Enable scribe client (deprecated)
  scribe-url:
    description: Scribe API Url
  structured:
    description: Enable structured logger
  timeout:
    description: Timeout duration
  verbose:
    description: Log verbosity level [-v,--verbose=1] = info, [-vv,--verbose=2] = debug
runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/valint:v1.5.14
  args:
    - slsa
    - ${{ inputs.target }}
    - ${{ inputs.all-env && '--all-env=' }}${{ inputs.all-env }}
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.build-type && '--build-type=' }}${{ inputs.build-type }}
    - ${{ inputs.builder-id && '--builder-id=' }}${{ inputs.builder-id }}
    - ${{ inputs.by-product && '--by-product=' }}${{ inputs.by-product }}
    - ${{ inputs.ca && '--ca=' }}${{ inputs.ca }}
    - ${{ inputs.cert && '--cert=' }}${{ inputs.cert }}
    - ${{ inputs.components && '--components=' }}${{ inputs.components }}
    - ${{ inputs.crl && '--crl=' }}${{ inputs.crl }}
    - ${{ inputs.crl-full-chain && '--crl-full-chain=' }}${{ inputs.crl-full-chain }}
    - ${{ inputs.depth && '--depth=' }}${{ inputs.depth }}
    - ${{ inputs.disable-crl && '--disable-crl=' }}${{ inputs.disable-crl }}
    - ${{ inputs.external && '--external=' }}${{ inputs.external }}
    - ${{ inputs.finished-on && '--finished-on=' }}${{ inputs.finished-on }}
    - ${{ inputs.force && '--force=' }}${{ inputs.force }}
    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
    - ${{ inputs.git-auth && '--git-auth=' }}${{ inputs.git-auth }}
    - ${{ inputs.git-branch && '--git-branch=' }}${{ inputs.git-branch }}
    - ${{ inputs.git-commit && '--git-commit=' }}${{ inputs.git-commit }}
    - ${{ inputs.git-tag && '--git-tag=' }}${{ inputs.git-tag }}
    - ${{ inputs.invocation && '--invocation=' }}${{ inputs.invocation }}
    - ${{ inputs.key && '--key=' }}${{ inputs.key }}
    - ${{ inputs.kms && '--kms=' }}${{ inputs.kms }}
    - ${{ inputs.oci && '--oci=' }}${{ inputs.oci }}
    - ${{ inputs.oci-repo && '--oci-repo=' }}${{ inputs.oci-repo }}
    - ${{ inputs.pass && '--pass=' }}${{ inputs.pass }}
    - ${{ inputs.payload && '--payload=' }}${{ inputs.payload }}
    - ${{ inputs.platform && '--platform=' }}${{ inputs.platform }}
    - ${{ inputs.predicate && '--predicate=' }}${{ inputs.predicate }}
    - ${{ inputs.pubkey && '--pubkey=' }}${{ inputs.pubkey }}
    - ${{ inputs.started-on && '--started-on=' }}${{ inputs.started-on }}
    - ${{ inputs.statement && '--statement=' }}${{ inputs.statement }}
    - ${{ inputs.cache-enable && '--cache-enable=' }}${{ inputs.cache-enable }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - --context-type=github
    - ${{ inputs.deliverable && '--deliverable=' }}${{ inputs.deliverable }}
    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
    - ${{ inputs.gate && '--gate=' }}${{ inputs.gate }}
    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
    - ${{ inputs.level && '--level=' }}${{ inputs.level }}
    - ${{ inputs.log-context && '--log-context=' }}${{ inputs.log-context }}
    - ${{ inputs.log-file && '--log-file=' }}${{ inputs.log-file }}
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    - ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }}
    - ${{ inputs.pipeline-name && '--pipeline-name=' }}${{ inputs.pipeline-name }}
    - ${{ inputs.predicate-type && '--predicate-type=' }}${{ inputs.predicate-type }}
    - ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }}
    - ${{ inputs.product-version && '--product-version=' }}${{ inputs.product-version }}
    - ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }}
    - ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }}
    - ${{ inputs.scribe-disable && '--scribe.disable=' }}${{ inputs.scribe-disable }}
    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.structured && '--structured=' }}${{ inputs.structured }}
    - ${{ inputs.timeout && '--timeout=' }}${{ inputs.timeout }}
    - ${{ inputs.verbose && '--verbose=' }}${{ inputs.verbose }}
branding:
  icon: shield
  color: green
